export let hexaMove = {
    'n-resize':[{'d':'ne','p':3},{'d':'nw','p':3}],                
    'e-resize':[{'d':'ne','p':0},{'d':'se','p':0}],
    's-resize':[{'d':'se','p':3},{'d':'sw','p':3}],
    'w-resize':[{'d':'nw','p':0},{'d':'sw','p':0}],
    'ne-resize':[{'d':'ne','p':0},{'d':'se','p':0}],
    'nw-resize':[{'d':'nw','p':0},{'d':'sw','p':0}],
    'se-resize':[{'d':'se','p':1},{'d':'se','p':2}],
    'sw-resize':[{'d':'sw','p':1},{'d':'sw','p':2}]
    },
    hexaFusion = {
    'n':[
        {'nh':'n','cp':[
            {'d':'se','p':[
                {'bp':'se','v':0},
                {'bp':'se','v':1},
                {'bp':'se','v':2},
                {'ph':2,'bx':'-','by':'+'}                        
            ]},
            {'d':'sw','p':[
                {'bp':'sw','v':0},
                {'bp':'sw','v':1},
                {'bp':'sw','v':2},
                {'ph':1,'bx':'+','by':'+'}                        
            ]}
            ],'dp':[]},
        {'cp':[
            {'d':'ne','p':[
                {'bp':'ne','v':0},
                {'bp':'ne','v':1},
                {'bp':'ne','v':2},
                {'ph':4,'bx':'-','by':'+'}                        
            ]},
            {'d':'nw','p':[
                {'bp':'nw','v':0},
                {'bp':'nw','v':1},
                {'bp':'nw','v':2},
                {'ph':5,'bx':'+','by':'+'}                        
            ]}
            ],'dp':[]}                        
    ],
    'ne':[
        {'nh':'ne','cp':[
            {'d':'sw','p':[
                {'bp':'sw','v':3},
                {'bp':'sw','v':3},
                {'ph':1,'bx':'-','by':'-'},                        
                {'ph':1,'bx':'-','by':'-'}                        
            ]},
            {'d':'nw','ifnot':['nwn'],'p':[
                {'bp':'nw','v':3},
                {'bp':'nw','v':2},
                {'bp':'nw','v':1},
                {'ph':0,'bx':'+','by':'+'}                        
            ]}
            ],'dp':[]},
        {'cp':[
            {'d':'ne','p':[
                {'bp':'ne','v':3},
                {'bp':'ne','v':2},
                {'ph':4,'bx':'+','by':'+'},                        
                {'ph':4,'bx':'+','by':'+'}                        
            ]},
            {'d':'se','p':[
                {'bp':'se','v':3},
                {'bp':'se','v':2},
                {'bp':'se','v':1},
                {'ph':3,'bx':'-','by':'-'}                        
            ]}
            ],'dp':[]}                        
    ],
    'nw':[
        {'nh':'nw','cp':[
            {'d':'ne','ifnot':['nen'],'p':[
                {'bp':'ne','v':3},
                {'bp':'ne','v':2},
                {'bp':'ne','v':1},
                {'ph':3,'bx':'-','by':'+'}                        
            ]},
            {'d':'se','p':[
                {'ph':2,'bx':'+','by':'-'},                        
                {'ph':2,'bx':'+','by':'-'},                       
                {'bp':'se','v':2},
                {'bp':'se','v':3}
            ]}
            ],'dp':[]},
        {'cp':[
            {'d':'nw','p':[
                {'ph':5,'bx':'-','by':'+'},                        
                {'ph':5,'bx':'-','by':'+'},                        
                {'bp':'nw','v':2},
                {'bp':'nw','v':3},
            ]},
            {'d':'sw','p':[
                {'bp':'sw','v':3},
                {'bp':'sw','v':2},
                {'bp':'sw','v':1},
                {'ph':0,'bx':'+','by':'-'}                        
            ]}
            ],'dp':[]}                        
    ],
    's':[
        {'nh':'s','cp':[
            {'d':'ne','p':[
                {'bp':'ne','v':0},
                {'bp':'ne','v':1},
                {'bp':'ne','v':2},
                {'ph':4,'bx':'-','by':''}                        
            ]},
            {'d':'nw','p':[
                {'bp':'nw','v':0},
                {'bp':'nw','v':1},
                {'bp':'nw','v':2},
                {'ph':5,'bx':'+','by':''}                        
            ]}
            ],'dp':[]},
        {'cp':[
            {'d':'se','p':[
                {'bp':'se','v':0},
                {'bp':'se','v':1},
                {'bp':'se','v':2},
                {'ph':2,'bx':'-','by':''}                        
            ]},
            {'d':'sw','p':[
                {'bp':'sw','v':0},
                {'bp':'sw','v':1},
                {'bp':'sw','v':2},
                {'ph':1,'bx':'+','by':''}                        
            ]}
            ],'dp':[]}                        
    ],
    'se':[
        {'nh':'se','cp':[
            {'d':'nw','p':[
                {'bp':'nw','v':3},
                {'bp':'nw','v':3},
                {'ph':5,'bx':'-','by':'+'},                        
                {'ph':5,'bx':'-','by':'+'}                        
            ]},
            {'d':'sw','p':[
                {'bp':'sw','v':3},
                {'bp':'sw','v':2},
                {'bp':'sw','v':1},
                {'ph':0,'bx':'+','by':'-'}                        
            ]}
            ],'dp':[]},
        {'cp':[
            {'d':'se','p':[
                {'bp':'se','v':3},
                {'bp':'se','v':2},
                {'ph':2,'bx':'+','by':'-'},                        
                {'ph':2,'bx':'+','by':'-'}                        
            ]},
            {'d':'ne','p':[
                {'bp':'ne','v':3},
                {'bp':'ne','v':2},
                {'bp':'ne','v':1},
                {'ph':3,'bx':'-','by':'+'}                        
            ]}
            ],'dp':[]}                        
    ],
    'sw':[
        {'nh':'sw','ifnot':['nse'],'cp':[
            {'d':'ne','p':[
                {'bp':'ne','v':3},
                {'bp':'ne','v':3},
                {'ph':4,'bx':'+','by':'+'},                        
                {'ph':4,'bx':'+','by':'+'}                        
            ]},
            {'d':'se','p':[
                {'bp':'se','v':3},
                {'bp':'se','v':2},
                {'bp':'se','v':1},
                {'ph':3,'bx':'-','by':'-'}                        
            ]}
            ],'dp':[]},
        {'cp':[
            {'d':'sw','p':[
                {'bp':'sw','v':3},
                {'bp':'sw','v':3},
                {'ph':1,'bx':'-','by':'-'},                        
                {'ph':1,'bx':'-','by':'-'}                        
            ]},
            {'d':'nw','p':[
                {'ph':0,'bx':'+','by':'+'},                        
                {'bp':'nw','v':1},
                {'bp':'nw','v':2},
                {'bp':'nw','v':3}
            ]}
            ],'dp':[]}                        
    ],
    'n,ne':[
        {'nh':'n','cp':[
            {'d':'sw','p':[
                {'bp':'sw','v':0},
                {'bp':'sw','v':1},
                {'bp':'sw','v':2},
                {'ph':1,'bx':'+','by':''}                        
            ]}
            ],'dp':['se']},
        {'nh':'ne','cp':[
            {'d':'sw','p':[
                {'bp':'sw','v':3},
                {'bp':'sw','v':2},
                {'ph':1,'bx':'-','by':'-'},
                {'ph':1,'bx':'-','by':'-'}                        
            ]},
            {'d':'ne','p':[
                {'bp':'ne','v':0},
                {'bp':'ne','v':1},
                {'bp':'ne','v':2},
                {'bp':'ne','v':3}                        
            ]}
            ],'dp':[]},
        {'cp':[
            {'d':'nw','p':[
                {'bp':'nw','v':0},
                {'bp':'nw','v':1},
                {'bp':'nw','v':2},
                {'ph':5,'bx':'+','by':''}                        
            ]},
            {'d':'se','p':[
                {'bp':'se','v':3},
                {'bp':'se','v':2},
                {'bp':'se','v':1},
                {'ph':3,'bx':'-','by':'-'}                        
            ]}
            ],'dp':['ne']}                        
    ],            
    'n,nw':[
        {'nh':'n','cp':['getPointsFusion_n_n_se'],'dp':['sw']},
        {'nh':'nw','cp':['getPointsFusion_sw_sw_ne','getPointsFusion_nw_nw_se'],'dp':[]},
        {'cp':['getPointsFusion_s_s_ne','getPointsFusion_se_se_sw'],'dp':['nw']}                        
    ],            
    'ne,se':[
        {'nh':'ne','cp':[
            {'d':'nw','p':[
                {'bp':'nw','v':3},
                {'bp':'nw','v':2},
                {'bp':'nw','v':1},
                {'ph':0,'bx':'+','by':'+'}                        
            ]},
            {'d':'se','p':[
                {'bp':'se','v':0},
                {'bp':'se','v':1},
                {'bp':'se','v':2},
                {'ph':2,'bx':'-','by':'-'}                        
            ]}
            ],'dp':['sw']},
        {'nh':'se','cp':[
            {'d':'sw','p':[
                {'bp':'sw','v':3},
                {'bp':'sw','v':2},
                {'bp':'sw','v':1},
                {'ph':0,'bx':'+','by':'-'}                        
            ]},
            {'d':'ne','p':[
                {'bp':'ne','v':0},
                {'bp':'ne','v':1},
                {'bp':'ne','v':2},
                {'ph':4,'bx':'-','by':'-'}                        
            ]}
            ],'dp':['nw']},
        {'cp':[
            {'d':'ne','p':[
                {'bp':'nw','v':3},
                {'bp':'nw','v':2},
                {'ph':4,'bx':'+','by':'+'},                        
                {'ph':4,'bx':'+','by':'+'}                        
            ]},
            {'d':'se','p':[
                {'bp':'se','v':3},
                {'bp':'se','v':2},
                {'ph':2,'bx':'+','by':'-'},                        
                {'ph':2,'bx':'+','by':'-'}                        
            ]}
            ],'dp':[]}                        
    ],
    'sw,nw':[
        {'nh':'sw','cp':['getPointsFusion_sw_sw_ne'],'dp':['ne']},
        {'nh':'nw','cp':['getPointsFusion_nw_nw_se','getPointsFusion_nw_nw_se'],'dp':[]},
        {'cp':['getPointsFusion_se_se_nw','getPointsFusion_ne_ne_sw'],'dp':[]}                        
    ],            
    'ne,sw':[
        {'cp':['getPointsFusion_sw_sw_ne','getPointsFusion_ne_ne_sw'],'dp':[]}
    ],
    'n,s':[
        {'cp':['getPointsFusion_n_n_se','getPointsFusion_n_n_sw','getPointsFusion_s_s_nw','getPointsFusion_s_s_ne'],'dp':[]}
    ],
    'se,nw':[
        {'cp':['getPointsFusion_se_se_nw','getPointsFusion_se_se_sw','getPointsFusion_nw_nw_ne','getPointsFusion_nw_nw_se'],'dp':[]}
    ],
    'ne,nw':[
        {'cp':['getPointsFusion_se_se_nw','getPointsFusion_se_se_sw','getPointsFusion_sw_sw_ne','getPointsFusion_sw_sw_se'],'dp':[]}
    ],
    's,sw':[
        {'cp':['getPointsFusion_n_n_se','getPointsFusion_ne_ne_nw'],'dp':['sw']}
    ],
    'se,s':[
        {'nh':'s','cp':['getPointsFusion_s_s_nw'],'dp':['ne']},
        {'cp':['getPointsFusion_n_n_sw'],'dp':['se']}
    ],
    'se,sw':[
        //{'nh':'s','cp':['getPointsFusion_s_s_nw'],'dp':['ne']},
        {'cp':['getPointsFusion_nw_nw_se','getPointsFusion_nw_nw_ne','getPointsFusion_ne_ne_sw','getPointsFusion_ne_ne_nw'],'dp':[]}
    ],
    
                        
};
export function getPointsFusion(k,nh,d){
    let dp = hexaFusion[k].filter(f=>f.nh==nh)[0].cp.filter(cp=>cp.d==d)[0];
    if(!dp)console.log('points introuvable : '+k+','+nh+','+d);
    return dp;
}
